# 04. Feature Engineering

## Objective
- Develop features that capture seasonal and temporal patterns in electricity consumption.
- Prepare structured and informative input variables for Machine Learning and Deep Learning models.

## 1. Setup and Load Dataset

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Add project root to path
import os
import sys
sys.path.append(os.path.abspath('../'))
from src.data_loader import load_data, save_file
from src.features import create_static_features, create_holidays_features

# Visualization settings
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)

print(f"Python version: {sys.version.split()[0]}")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Python version: 3.10.11
Pandas version: 2.1.4
NumPy version: 1.26.4

In [2]:
# Load data using custom loader
try:
    df = load_data('data/processed/data_cleaned.parquet')
    print("Data loaded successfully!")
    print(f"Shape: {df.shape}")
    print(f"Time span: {df.index.min()} → {df.index.max()}")
    if not df.index.freq:
        df = df.asfreq("1H")
    print(f"Frequency: {df.index.freq}")
except Exception as e:
    print(f"[Error] {e}")

Loading: data/processed/data_cleaned.parquet
Data loaded successfully!
Shape: (35064, 371)
Time span: 2011-01-01 00:00:00 → 2014-12-31 23:00:00
Frequency: <Hour>

In [3]:
df_total = df[['total_load']].copy()

df_total.head()

                       total_load
Timestamp
2011-01-01 00:00:00  51764.567568
2011-01-01 01:00:00  66344.627687
2011-01-01 02:00:00  65981.054883
2011-01-01 03:00:00  66576.533566
2011-01-01 04:00:00  64963.552675

## 2. Static Features

In [4]:
# Execute
df_features = create_static_features(df_total)

# Verify data
print("Static feature columns:")
print(df_features.columns.tolist())
df_features.head()

Static feature columns:
['total_load', 'hour', 'month', 'day_of_week', 'day_of_month', 'day_of_year', 'hour_sin', 'hour_cos', 'year_sin', 'year_cos']

,total_load,hour,month,day_of_week,day_of_month,day_of_year,hour_sin,hour_cos,year_sin,year_cos
Timestamp,,,,,,,,,,
2011-01-01 00:00:00,51764.567568,0,1,5,1,1,0.000000,1.000000,0.0,1.0
2011-01-01 01:00:00,66344.627687,1,1,5,1,1,0.258819,0.965926,0.0,1.0
2011-01-01 02:00:00,65981.054883,2,1,5,1,1,0.500000,0.866025,0.0,1.0
2011-01-01 03:00:00,66576.533566,3,1,5,1,1,0.707107,0.707107,0.0,1.0
2011-01-01 04:00:00,64963.552675,4,1,5,1,1,0.866025,0.500000,0.0,1.0

## 3. Holidays Features

In [5]:
df_final = create_holidays_features(df_features)
df_final.head()

,total_load,hour,month,day_of_week,day_of_month,day_of_year,hour_sin,hour_cos,year_sin,year_cos,holiday_name
Timestamp,,,,,,,,,,,
2011-01-01 00:00:00,51764.567568,0,1,5,1,1,0.000000,1.000000,0.0,1.0,Ano Novo
2011-01-01 01:00:00,66344.627687,1,1,5,1,1,0.258819,0.965926,0.0,1.0,Ano Novo
2011-01-01 02:00:00,65981.054883,2,1,5,1,1,0.500000,0.866025,0.0,1.0,Ano Novo
2011-01-01 03:00:00,66576.533566,3,1,5,1,1,0.707107,0.707107,0.0,1.0,Ano Novo
2011-01-01 04:00:00,64963.552675,4,1,5,1,1,0.866025,0.500000,0.0,1.0,Ano Novo

## Save data

In [6]:
save_file(df_final,"data_total_features.parquet")

File saved as: ../data/processed\data_total_features.parquet

## 4. Conclusion
Feature engineering was performed exclusively on the total_load column, which aggregates electricity consumption across all 370 customers in the dataset. Calendar features such as hour, day of week, day of month, and month were extracted from the timestamp index to help the model understand temporal patterns. Cyclical sine/cosine transformations were applied to the hour and day-of-year fields, ensuring that the model correctly perceives the circular nature of daily and annual cycles rather than treating them as linear values. Portuguese public holidays were also encoded as categorical features, allowing the model to distinguish between regular and holiday consumption behavior. This refined dataset captures daily and weekly seasonality, short-term dependency, and short-term variability, making it suitable for time series forecasting models.

---

**Next Notebook:** [05_models_statistical.ipynb](05_models_statistical.ipynb) - Baseline and Statistical Models