# 06. Machine Learning Models

In [24]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Add project root to path
import os
import sys
sys.path.append(os.path.abspath('../'))
from src.data_loader import load_data, save_file
from src.splitting import split_train_test
from src.evaluation import evaluate, highlight_table
from src.models.baseline import naive_forecast, seasonal_naive_forecast
from src.models.ml import *

# Visualization settings
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)

print(f"Python version: {sys.version.split()[0]}")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Python version: 3.10.11
Pandas version: 2.1.4
NumPy version: 1.26.4

In [25]:
# Load data using custom loader
try:
    df = load_data('data/processed/data_total_features.parquet')
    print("Data loaded successfully!")
    print(f"Shape: {df.shape}")
    print(f"Time span: {df.index.min()} → {df.index.max()}")
    if not df.index.freq:
        df = df.asfreq("1H")
    print(f"Frequency: {df.index.freq}")
except Exception as e:
    print(f"[Error] {e}")

Loading: data/processed/data_total_features.parquet
Data loaded successfully!
Shape: (35064, 11)
Time span: 2011-01-01 00:00:00 → 2014-12-31 23:00:00
Frequency: <Hour>

In [26]:
df_split = df.copy()
df_split = df_split[df.index >= "2012-01-01"]
df_split.head()

,total_load,hour,month,day_of_week,day_of_month,day_of_year,hour_sin,hour_cos,year_sin,year_cos,holiday_name
Timestamp,,,,,,,,,,,
2012-01-01 00:00:00,104230.493821,0,1,6,1,1,0.000000,1.000000,0.0,1.0,Ano Novo
2012-01-01 01:00:00,112550.368868,1,1,6,1,1,0.258819,0.965926,0.0,1.0,Ano Novo
2012-01-01 02:00:00,110930.247627,2,1,6,1,1,0.500000,0.866025,0.0,1.0,Ano Novo
2012-01-01 03:00:00,106191.754971,3,1,6,1,1,0.707107,0.707107,0.0,1.0,Ano Novo
2012-01-01 04:00:00,103540.419166,4,1,6,1,1,0.866025,0.500000,0.0,1.0,Ano Novo

In [27]:
X_train, X_test, y_train, y_test, _ = split_train_test(df_split, 'total_load', split_time="2014-01-01", categorical_cols='holiday_name')

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (17568, 10)
Test shape: (8759, 10)

## 1. Baseline

In [28]:
# Naive forecast
seasonal_naive_pred = seasonal_naive_forecast(df_split, y_test, season=365)

# Evaluate forecasts
seasonal_naive_metrics = evaluate(y_test, seasonal_naive_pred)

print("Seasonal Naive (24h):", seasonal_naive_metrics)

Seasonal Naive (24h): {'MAE': 14598.19, 'RMSE': 21626.9, 'MAPE': 6.07}

## 2. Models

### 2.1 Random Forest

In [ ]:
rdf, rdf_pred = random_forest_model(X_train, y_train, X_test)
rdf_metrics = evaluate(y_test, rdf_pred)

print("Random Forest:", rdf_metrics)

LightGBM: {'MAE': 13265.68, 'RMSE': 19425.27, 'MAPE': 5.56}

### 2.2 LightGBM

In [30]:
lgbm, lgbm_pred = lightgbm_model(X_train, y_train, X_test)
lgbm_metrics = evaluate(y_test, lgbm_pred)

print("LightGBM:", lgbm_metrics)

LightGBM: {'MAE': 13629.68, 'RMSE': 19854.71, 'MAPE': 5.8}

### 2.3 XGBoost

In [31]:
xgb, xgb_pred = xgboost_model(X_train, y_train, X_test)
xgb_metrics = evaluate(y_test, xgb_pred)

print("XGBoost:", xgb_metrics)

XGBoost: {'MAE': 13570.01, 'RMSE': 20275.23, 'MAPE': 5.63}

## 3. Revive 2011

In [32]:
import requests
import numpy as np
import pandas as pd
from lightgbm import LGBMRegressor
from sklearn.compose import TransformedTargetRegressor

# Đảm bảo df_clean gốc được sắp xếp chuẩn theo DatetimeIndex
df_clean = df.sort_index()
target = 'total_load'

print("--- BẮT ĐẦU QUY TRÌNH: TẢI API THỜI TIẾT & PHỤC DỰNG 2011 ---")

# =========================================================================
# BƯỚC 1: TẢI DỮ LIỆU THỜI TIẾT TỪ OPEN-METEO API (MIỄN PHÍ)
# =========================================================================
# Sử dụng tọa độ Lisbon, Bồ Đào Nha (Lat: 38.7167, Lon: -9.1333) làm proxy
# Chỉ cần tải từ 2011-01-01 đến 2013-12-31 (phục vụ riêng cho Backcasting)
print("1. Đang kết nối API Open-Meteo tải dữ liệu thời tiết quá khứ...")

url = (
    "https://archive-api.open-meteo.com/v1/archive?"
    "latitude=38.7167&longitude=-9.1333"
    "&start_date=2011-01-01&end_date=2013-12-31"
    "&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m"
    "&timezone=Europe%2FLisbon"
)

response = requests.get(url)
if response.status_code != 200:
    raise Exception(f"Lỗi tải API: {response.text}")

data = response.json()
hourly = data['hourly']

# Chuyển đổi JSON thành DataFrame
df_weather_api = pd.DataFrame({
    'time': pd.to_datetime(hourly['time']),
    'temp': hourly['temperature_2m'],
    'humidity': hourly['relative_humidity_2m'],
    'wind_speed': hourly['wind_speed_10m']
}).set_index('time')

# Loại bỏ thông tin múi giờ (tz-naive) để an toàn gộp với df_clean của bạn
if df_weather_api.index.tz is not None:
    df_weather_api.index = df_weather_api.index.tz_localize(None)

print(f"-> Tải thành công {len(df_weather_api)} dòng dữ liệu thời tiết!")


# =========================================================================
# BƯỚC 2: GỘP DỮ LIỆU & FEATURE ENGINEERING THỜI TIẾT
# =========================================================================
print("2. Gộp dữ liệu và trích xuất các đặc trưng khí hậu bậc cao...")

# Gộp (Join) thời tiết vào bản sao của df_clean dựa trên khớp mốc giờ
df_process = df_clean.loc['2011-01-01':'2013-12-31'].copy()
df_process = df_process.join(df_weather_api, how='left')

# Xử lý nội suy nếu API có sót vài giờ ngẫu nhiên
df_process[['temp', 'humidity', 'wind_speed']] = df_process[['temp', 'humidity', 'wind_speed']].interpolate(method='time')

# --- Tạo Features Khí hậu ---
# 2.1. CDD/HDD (Làm mát > 18°C, Sưởi ấm < 15°C)
df_process['CDD'] = np.maximum(0, df_process['temp'] - 18)
df_process['HDD'] = np.maximum(0, 15 - df_process['temp'])
df_process['CDD_squared'] = df_process['CDD'] ** 2

# 2.2. Quán tính nhiệt (Ngậm nhiệt sau 3 ngày nắng gắt)
df_process['temp_rolling_mean_72h'] = df_process['temp'].rolling(window=72).mean()

# 2.3. Chỉ số oi bức (Apparent Temperature / THI)
T = df_process['temp']
RH = df_process['humidity']
df_process['THI_Apparent'] = T - (0.55 - 0.0055 * RH) * (T - 14.5)

# 2.4. Gió làm mát khi trời đang nóng
df_process['wind_cooling_effect'] = df_process['wind_speed'] * df_process['CDD']

# 2.5. Tương tác hành vi: Giờ x Nhiệt độ
if 'hour' in df_process.columns:
    df_process['hour_x_CDD'] = df_process['hour'] * df_process['CDD']

# Lấp đầy mốc NaN do rolling ở các dòng đầu
df_process = df_process.bfill()


# =========================================================================
# BƯỚC 3: HUẤN LUYỆN "CỖ MÁY THỜI GIAN" VỚI LIGHTGBM
# =========================================================================
# Lấy toàn bộ features ngoại sinh gốc + features thời tiết vừa tạo
exo_features = [col for col in df_process.columns if col != target]

# Tập Train: Giai đoạn trưởng thành (2012 và 2013)
X_train_stable = df_process.loc['2012-01-01':'2013-12-31', exo_features]
y_train_stable = df_process.loc['2012-01-01':'2013-12-31', target]

# Tập Cần phục dựng (Hindcast): Toàn bộ năm 2011
X_backcast_2011 = df_process.loc['2011-01-01':'2011-12-31', exo_features]

lgbm_core = LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.03,
    num_leaves=63,
    colsample_bytree=0.7,
    random_state=42,
    n_jobs=-1
)

backcast_model = TransformedTargetRegressor(
    regressor=lgbm_core,
    func=np.log1p,
    inverse_func=np.expm1
)

print("3. Đang huấn luyện mô hình học quy luật tải theo thời tiết từ 2012-2013...")
backcast_model.fit(X_train_stable, y_train_stable)


# =========================================================================
# BƯỚC 4: TÁI TẠO 2011 & TRẢ VỀ KẾT QUẢ SẠCH (BỎ THỜI TIẾT)
# =========================================================================
print("4. Đang ánh xạ ngược để tái tạo sản lượng điện năm 2011...")
y_synthetic_2011 = backcast_model.predict(X_backcast_2011)

# Lấy lại tập df_clean GỐC của bạn (để đảm bảo không dính dáng gì đến cột thời tiết)
df_2011 = df.copy()

# THAY THẾ HOÀN TOÀN tải điện thô 2011 bằng chuỗi tổng hợp chuẩn thời tiết
df_2011.loc['2011-01-01':'2011-12-31', target] = y_synthetic_2011

print("--- HOÀN TẤT QUY TRÌNH! ---")
print("-> Toàn bộ dữ liệu thời tiết tải từ API đã làm xong nhiệm vụ đòn bẩy và ĐÃ BỊ LOẠI BỎ.")
print("-> Tập df_2011 hiện tại giữ nguyên cấu trúc cột ban đầu của bạn.")
print("-> Đỉnh tải điện 2011 đã được nâng khớp hoàn hảo. Bạn có thể tạo lag_365 ngay!")

--- BẮT ĐẦU QUY TRÌNH: TẢI API THỜI TIẾT & PHỤC DỰNG 2011 ---
1. Đang kết nối API Open-Meteo tải dữ liệu thời tiết quá khứ...
-> Tải thành công 26304 dòng dữ liệu thời tiết!
2. Gộp dữ liệu và trích xuất các đặc trưng khí hậu bậc cao...
3. Đang huấn luyện mô hình học quy luật tải theo thời tiết từ 2012-2013...
4. Đang ánh xạ ngược để tái tạo sản lượng điện năm 2011...
--- HOÀN TẤT QUY TRÌNH! ---
-> Toàn bộ dữ liệu thời tiết tải từ API đã làm xong nhiệm vụ đòn bẩy và ĐÃ BỊ LOẠI BỎ.
-> Tập df_2011 hiện tại giữ nguyên cấu trúc cột ban đầu của bạn.
-> Đỉnh tải điện 2011 đã được nâng khớp hoàn hảo. Bạn có thể tạo lag_365 ngay!

In [33]:
df_2011.head()

,total_load,hour,month,day_of_week,day_of_month,day_of_year,hour_sin,hour_cos,year_sin,year_cos,holiday_name
Timestamp,,,,,,,,,,,
2011-01-01 00:00:00,128273.479673,0,1,5,1,1,0.000000,1.000000,0.0,1.0,Ano Novo
2011-01-01 01:00:00,109173.297911,1,1,5,1,1,0.258819,0.965926,0.0,1.0,Ano Novo
2011-01-01 02:00:00,105270.467688,2,1,5,1,1,0.500000,0.866025,0.0,1.0,Ano Novo
2011-01-01 03:00:00,103119.465761,3,1,5,1,1,0.707107,0.707107,0.0,1.0,Ano Novo
2011-01-01 04:00:00,100037.338338,4,1,5,1,1,0.866025,0.500000,0.0,1.0,Ano Novo

In [34]:
X_train, X_test, y_train, y_test, _ = split_train_test(df_2011, 'total_load', split_time="2014-01-01", categorical_cols='holiday_name')

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (26328, 10)
Test shape: (8759, 10)

In [35]:
rdf, rdf_pred = random_forest_model(X_train, y_train, X_test)
rdf_metrics = evaluate(y_test, rdf_pred)

print("Random Forest:", rdf_metrics)

Random Forest: {'MAE': 12828.45, 'RMSE': 18776.22, 'MAPE': 5.36}

In [36]:
lgbm, lgbm_pred = lightgbm_model(X_train, y_train, X_test)
lgbm_metrics = evaluate(y_test, lgbm_pred)

print("LightGBM:", lgbm_metrics)

LightGBM: {'MAE': 13012.48, 'RMSE': 18869.57, 'MAPE': 5.58}

In [37]:
xgb, xgb_pred = xgboost_model(X_train, y_train, X_test)
xgb_metrics = evaluate(y_test, xgb_pred)

print("XGBoost:", xgb_metrics)

XGBoost: {'MAE': 12965.75, 'RMSE': 19446.47, 'MAPE': 5.37}

## 4. Optimization

In [56]:
from src.models.optimizations import *

c:\Users\YOGA\Desktop\01_Time Series\PROJECT\Github\main\Electricity-Load-Diagrams\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [61]:
df_optimize = df_2011.copy()
df_optimize = df_optimize[df.index < '2014-01-01']
df_optimize.head()

,total_load,hour,month,day_of_week,day_of_month,day_of_year,hour_sin,hour_cos,year_sin,year_cos,holiday_name
Timestamp,,,,,,,,,,,
2011-01-01 00:00:00,128273.479673,0,1,5,1,1,0.000000,1.000000,0.0,1.0,Ano Novo
2011-01-01 01:00:00,109173.297911,1,1,5,1,1,0.258819,0.965926,0.0,1.0,Ano Novo
2011-01-01 02:00:00,105270.467688,2,1,5,1,1,0.500000,0.866025,0.0,1.0,Ano Novo
2011-01-01 03:00:00,103119.465761,3,1,5,1,1,0.707107,0.707107,0.0,1.0,Ano Novo
2011-01-01 04:00:00,100037.338338,4,1,5,1,1,0.866025,0.500000,0.0,1.0,Ano Novo

In [ ]:
X_train, X_valid, y_train, y_valid, _ = split_train_test(df_optimize, 'total_load', split_time="2013-01-01", categorical_cols='holiday_name')

print("Train shape:", X_train.shape)
print("Val shape:", X_valid.shape)

Train shape: (17568, 10)
Test shape: (8759, 10)

In [72]:
rdf_best = optuna_random_forest(X_train, y_train, X_valid, y_valid, n_trials=50)

[I 2026-05-12 20:54:12,691] A new study created in memory with name: no-name-b80955f3-9192-4c26-bc0e-4c66aa99b5a5
[I 2026-05-12 20:54:14,665] Trial 0 finished with value: 20794.616670641557 and parameters: {'n_estimators': 437, 'max_depth': 48, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': 0.5780093202212182}. Best is trial 0 with value: 20794.616670641557.
[I 2026-05-12 20:54:15,899] Trial 1 finished with value: 20549.199834501498 and parameters: {'n_estimators': 240, 'max_depth': 12, 'min_samples_split': 18, 'min_samples_leaf': 7, 'max_features': 0.8540362888980227}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:16,459] Trial 2 finished with value: 20765.13226391077 and parameters: {'n_estimators': 118, 'max_depth': 49, 'min_samples_split': 17, 'min_samples_leaf': 3, 'max_features': 0.5909124836035503}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:17,783] Trial 3 finished with value: 20883.855046794895 and parameters: {'n_estimators': 265, 'max_depth': 22, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 0.645614570099021}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:21,496] Trial 4 finished with value: 20767.440217064926 and parameters: {'n_estimators': 651, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.728034992108518}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:24,990] Trial 5 finished with value: 20796.36892256574 and parameters: {'n_estimators': 807, 'max_depth': 18, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 0.5232252063599989}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:28,652] Trial 6 finished with value: 20781.265964377475 and parameters: {'n_estimators': 647, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 0.9828160165372797}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:33,222] Trial 7 finished with value: 20838.140323547334 and parameters: {'n_estimators': 828, 'max_depth': 22, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_features': 0.7200762468698007}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:34,242] Trial 8 finished with value: 20743.590059454535 and parameters: {'n_estimators': 209, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 0.6293899908000085}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:37,451] Trial 9 finished with value: 20814.48010313903 and parameters: {'n_estimators': 696, 'max_depth': 22, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 0.5924272277627636}. Best is trial 1 with value: 20549.199834501498.
[I 2026-05-12 20:54:39,611] Trial 10 finished with value: 20322.4599071021 and parameters: {'n_estimators': 421, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 0.916815832829975}. Best is trial 10 with value: 20322.4599071021.
[I 2026-05-12 20:54:41,588] Trial 11 finished with value: 20288.33560060359 and parameters: {'n_estimators': 415, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 0.8822343758608416}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:54:43,663] Trial 12 finished with value: 20288.609060891235 and parameters: {'n_estimators': 420, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 0.8995879107630846}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:54:47,047] Trial 13 finished with value: 20698.179632701514 and parameters: {'n_estimators': 458, 'max_depth': 38, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 0.8283254019450633}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:54:49,443] Trial 14 finished with value: 20830.308986820637 and parameters: {'n_estimators': 368, 'max_depth': 31, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': 0.8138214726279749}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:54:54,508] Trial 15 finished with value: 20321.957357380375 and parameters: {'n_estimators': 970, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': 0.9947460358092146}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:54:58,097] Trial 16 finished with value: 20784.780256852333 and parameters: {'n_estimators': 548, 'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 2, 'max_features': 0.9047894591765571}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:02,364] Trial 17 finished with value: 21074.504114188134 and parameters: {'n_estimators': 544, 'max_depth': 39, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 0.9216277351959188}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:04,028] Trial 18 finished with value: 20692.780094199414 and parameters: {'n_estimators': 289, 'max_depth': 26, 'min_samples_split': 20, 'min_samples_leaf': 3, 'max_features': 0.7693196665032632}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:05,970] Trial 19 finished with value: 20731.692131878444 and parameters: {'n_estimators': 320, 'max_depth': 18, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 0.8869399965128487}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:08,734] Trial 20 finished with value: 20679.153740758 and parameters: {'n_estimators': 495, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 0.9462272180323188}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:10,660] Trial 21 finished with value: 20324.963220457394 and parameters: {'n_estimators': 370, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': 0.9859562237104099}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:15,448] Trial 22 finished with value: 20320.44703598836 and parameters: {'n_estimators': 968, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 0.9922632131395173}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:21,212] Trial 23 finished with value: 20751.604029742473 and parameters: {'n_estimators': 961, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 0.8639683161287113}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:26,517] Trial 24 finished with value: 20761.434625962585 and parameters: {'n_estimators': 819, 'max_depth': 19, 'min_samples_split': 18, 'min_samples_leaf': 2, 'max_features': 0.951631065900618}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:29,850] Trial 25 finished with value: 20554.501841604746 and parameters: {'n_estimators': 627, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 4, 'max_features': 0.8065643391207633}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:34,559] Trial 26 finished with value: 20760.121657545456 and parameters: {'n_estimators': 734, 'max_depth': 26, 'min_samples_split': 19, 'min_samples_leaf': 1, 'max_features': 0.955914115856001}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:35,483] Trial 27 finished with value: 20587.63916405657 and parameters: {'n_estimators': 166, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 0.7741045994082937}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:40,956] Trial 28 finished with value: 20806.20581333183 and parameters: {'n_estimators': 893, 'max_depth': 44, 'min_samples_split': 16, 'min_samples_leaf': 2, 'max_features': 0.870676204071043}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:42,848] Trial 29 finished with value: 20790.494254287514 and parameters: {'n_estimators': 387, 'max_depth': 36, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': 0.6907670542494437}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:45,939] Trial 30 finished with value: 20759.968521201983 and parameters: {'n_estimators': 489, 'max_depth': 26, 'min_samples_split': 19, 'min_samples_leaf': 1, 'max_features': 0.9253085663206508}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:50,601] Trial 31 finished with value: 20320.60717950404 and parameters: {'n_estimators': 965, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 0.9848024319125552}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:55:55,600] Trial 32 finished with value: 20497.955470718818 and parameters: {'n_estimators': 895, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 0.9577150885447347}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:56:02,014] Trial 33 finished with value: 20844.744224488528 and parameters: {'n_estimators': 998, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 0.996687454237993}. Best is trial 11 with value: 20288.33560060359.
[I 2026-05-12 20:56:06,041] Trial 34 finished with value: 20283.757525027682 and parameters: {'n_estimators': 914, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 0.8368078049885144}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:11,185] Trial 35 finished with value: 20780.573663210595 and parameters: {'n_estimators': 888, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 0.8473672972672979}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:14,411] Trial 36 finished with value: 20527.40288443212 and parameters: {'n_estimators': 593, 'max_depth': 14, 'min_samples_split': 19, 'min_samples_leaf': 1, 'max_features': 0.892740727469292}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:18,213] Trial 37 finished with value: 20683.91490711042 and parameters: {'n_estimators': 732, 'max_depth': 17, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': 0.786850883859199}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:19,804] Trial 38 finished with value: 20495.33278464104 and parameters: {'n_estimators': 316, 'max_depth': 12, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': 0.843653728594524}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:20,392] Trial 39 finished with value: 20781.213010717467 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 0.8812829080304143}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:21,817] Trial 40 finished with value: 20720.392394716935 and parameters: {'n_estimators': 213, 'max_depth': 50, 'min_samples_split': 20, 'min_samples_leaf': 2, 'max_features': 0.730847561732929}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:26,336] Trial 41 finished with value: 20324.687467895463 and parameters: {'n_estimators': 931, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': 0.9687211808750152}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:30,431] Trial 42 finished with value: 20426.904858282232 and parameters: {'n_estimators': 763, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.9334446397670175}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:35,196] Trial 43 finished with value: 20496.734348207563 and parameters: {'n_estimators': 853, 'max_depth': 12, 'min_samples_split': 17, 'min_samples_leaf': 3, 'max_features': 0.9079907962250575}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:41,243] Trial 44 finished with value: 20871.175935516523 and parameters: {'n_estimators': 937, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': 0.9708963589782699}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:46,955] Trial 45 finished with value: 20636.472089837836 and parameters: {'n_estimators': 998, 'max_depth': 14, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.8288638370714688}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:52,405] Trial 46 finished with value: 20811.079974099037 and parameters: {'n_estimators': 857, 'max_depth': 17, 'min_samples_split': 14, 'min_samples_leaf': 4, 'max_features': 0.9373131958762139}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:54,486] Trial 47 finished with value: 20341.13026906812 and parameters: {'n_estimators': 430, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 0.9004340225334944}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:56:57,827] Trial 48 finished with value: 20868.398542539075 and parameters: {'n_estimators': 470, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.9991417930830014}. Best is trial 34 with value: 20283.757525027682.
[I 2026-05-12 20:57:00,889] Trial 49 finished with value: 20819.00127285322 and parameters: {'n_estimators': 516, 'max_depth': 23, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': 0.8630000640823956}. Best is trial 34 with value: 20283.757525027682.

========================================
MODEL      : random_forest
BEST RMSE  : 20283.7575
BEST PARAMS:
{'n_estimators': 914, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 0.8368078049885144}
========================================

In [63]:
lgbm_best = optuna_lightgbm(X_train, y_train, X_valid, y_valid, n_trials=50)

[I 2026-05-12 20:45:57,045] A new study created in memory with name: no-name-6a8f0e84-4c3e-47b3-8569-2b1751870ee1
[I 2026-05-12 20:46:02,627] Trial 0 finished with value: 21549.73951115825 and parameters: {'n_estimators': 1311, 'learning_rate': 0.044635901521768134, 'max_depth': 10, 'num_leaves': 159, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'min_child_samples': 10, 'reg_alpha': 8.661761457749352, 'reg_lambda': 6.011150117432088}. Best is trial 0 with value: 21549.73951115825.
[I 2026-05-12 20:46:13,977] Trial 1 finished with value: 21264.912357945133 and parameters: {'n_estimators': 2212, 'learning_rate': 0.005242693862597309, 'max_depth': 12, 'num_leaves': 215, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'min_child_samples': 22, 'reg_alpha': 3.0424224295953772, 'reg_lambda': 5.247564316322379}. Best is trial 1 with value: 21264.912357945133.
[I 2026-05-12 20:46:16,517] Trial 2 finished with value: 21137.49535045469 and parameters: {'n_estimators': 1466, 'learning_rate': 0.009776854331372627, 'max_depth': 9, 'num_leaves': 48, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'min_child_samples': 48, 'reg_alpha': 7.851759613930136, 'reg_lambda': 1.9967378215835974}. Best is trial 2 with value: 21137.49535045469.
[I 2026-05-12 20:46:17,402] Trial 3 finished with value: 20540.646920387087 and parameters: {'n_estimators': 1688, 'learning_rate': 0.019560708142748476, 'max_depth': 3, 'num_leaves': 161, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'min_child_samples': 96, 'reg_alpha': 9.656320330745594, 'reg_lambda': 8.08397348116461}. Best is trial 3 with value: 20540.646920387087.
[I 2026-05-12 20:46:22,628] Trial 4 finished with value: 20656.572288565472 and parameters: {'n_estimators': 1122, 'learning_rate': 0.006260977143530196, 'max_depth': 9, 'num_leaves': 121, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'min_child_samples': 8, 'reg_alpha': 9.093204020787821, 'reg_lambda': 2.587799816000169}. Best is trial 3 with value: 20540.646920387087.
[I 2026-05-12 20:46:27,636] Trial 5 finished with value: 21306.8003710133 and parameters: {'n_estimators': 2089, 'learning_rate': 0.010248990260475094, 'max_depth': 8, 'num_leaves': 146, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'min_child_samples': 79, 'reg_alpha': 9.394989415641891, 'reg_lambda': 8.948273504276488}. Best is trial 3 with value: 20540.646920387087.
[I 2026-05-12 20:46:28,949] Trial 6 finished with value: 21042.569937441043 and parameters: {'n_estimators': 1914, 'learning_rate': 0.0417680537765588, 'max_depth': 3, 'num_leaves': 62, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'min_child_samples': 42, 'reg_alpha': 2.713490317738959, 'reg_lambda': 8.287375091519294}. Best is trial 3 with value: 20540.646920387087.
[I 2026-05-12 20:46:31,463] Trial 7 finished with value: 20693.733162996763 and parameters: {'n_estimators': 1263, 'learning_rate': 0.009547826400522689, 'max_depth': 8, 'num_leaves': 48, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'min_child_samples': 99, 'reg_alpha': 7.722447692966574, 'reg_lambda': 1.987156815341724}. Best is trial 3 with value: 20540.646920387087.
[I 2026-05-12 20:46:32,643] Trial 8 finished with value: 20870.76071107876 and parameters: {'n_estimators': 314, 'learning_rate': 0.03269124292259021, 'max_depth': 10, 'num_leaves': 190, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'min_child_samples': 39, 'reg_alpha': 1.1586905952512971, 'reg_lambda': 8.631034258755935}. Best is trial 3 with value: 20540.646920387087.
[I 2026-05-12 20:46:33,721] Trial 9 finished with value: 20443.716729792653 and parameters: {'n_estimators': 1983, 'learning_rate': 0.010711937478224529, 'max_depth': 3, 'num_leaves': 89, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'min_child_samples': 66, 'reg_alpha': 8.872127425763265, 'reg_lambda': 4.722149251619493}. Best is trial 9 with value: 20443.716729792653.
[I 2026-05-12 20:46:36,228] Trial 10 finished with value: 21478.69903262783 and parameters: {'n_estimators': 2885, 'learning_rate': 0.019484776564044022, 'max_depth': 5, 'num_leaves': 98, 'subsample': 0.8010124870699186, 'colsample_bytree': 0.9407901565064135, 'min_child_samples': 67, 'reg_alpha': 6.18718032094214, 'reg_lambda': 3.7200432627265183}. Best is trial 9 with value: 20443.716729792653.
[I 2026-05-12 20:46:37,640] Trial 11 finished with value: 20761.400502441462 and parameters: {'n_estimators': 2581, 'learning_rate': 0.018808482060509096, 'max_depth': 3, 'num_leaves': 97, 'subsample': 0.7737425087025644, 'colsample_bytree': 0.8920339412764792, 'min_child_samples': 96, 'reg_alpha': 6.071842740332256, 'reg_lambda': 6.880988980130585}. Best is trial 9 with value: 20443.716729792653.
[I 2026-05-12 20:46:38,440] Trial 12 finished with value: 20351.874370590678 and parameters: {'n_estimators': 722, 'learning_rate': 0.014335938848538895, 'max_depth': 5, 'num_leaves': 255, 'subsample': 0.7668689715046754, 'colsample_bytree': 0.8610724800899923, 'min_child_samples': 74, 'reg_alpha': 9.902412260216211, 'reg_lambda': 0.30925226388650984}. Best is trial 12 with value: 20351.874370590678.
[I 2026-05-12 20:46:39,259] Trial 13 finished with value: 20267.529911800157 and parameters: {'n_estimators': 669, 'learning_rate': 0.013477450689285447, 'max_depth': 5, 'num_leaves': 255, 'subsample': 0.8259247350993981, 'colsample_bytree': 0.8574753894882987, 'min_child_samples': 67, 'reg_alpha': 6.802998308648532, 'reg_lambda': 0.3286995785803954}. Best is trial 13 with value: 20267.529911800157.
[I 2026-05-12 20:46:40,176] Trial 14 finished with value: 20808.427331581373 and parameters: {'n_estimators': 606, 'learning_rate': 0.0288621869131641, 'max_depth': 6, 'num_leaves': 255, 'subsample': 0.8457495422882018, 'colsample_bytree': 0.8484362704050545, 'min_child_samples': 77, 'reg_alpha': 4.665740730554513, 'reg_lambda': 0.27405700502154856}. Best is trial 13 with value: 20267.529911800157.
[I 2026-05-12 20:46:41,006] Trial 15 finished with value: 20387.437871563558 and parameters: {'n_estimators': 749, 'learning_rate': 0.014193823249058763, 'max_depth': 5, 'num_leaves': 243, 'subsample': 0.8561711433906496, 'colsample_bytree': 0.8213334313517213, 'min_child_samples': 63, 'reg_alpha': 6.705451426048862, 'reg_lambda': 0.24779127567149034}. Best is trial 13 with value: 20267.529911800157.
[I 2026-05-12 20:46:42,116] Trial 16 finished with value: 20425.77363157018 and parameters: {'n_estimators': 782, 'learning_rate': 0.014085660474225126, 'max_depth': 6, 'num_leaves': 215, 'subsample': 0.7911302960155628, 'colsample_bytree': 0.8721955500879099, 'min_child_samples': 81, 'reg_alpha': 5.198679195412575, 'reg_lambda': 0.992616220694832}. Best is trial 13 with value: 20267.529911800157.
[I 2026-05-12 20:46:42,562] Trial 17 finished with value: 21687.75630263724 and parameters: {'n_estimators': 325, 'learning_rate': 0.007301448004505651, 'max_depth': 5, 'num_leaves': 220, 'subsample': 0.8505915654206465, 'colsample_bytree': 0.7758106106783651, 'min_child_samples': 53, 'reg_alpha': 7.3555051811565635, 'reg_lambda': 3.3405076606543123}. Best is trial 13 with value: 20267.529911800157.
[I 2026-05-12 20:46:43,406] Trial 18 finished with value: 21067.94995325892 and parameters: {'n_estimators': 1067, 'learning_rate': 0.026443898966806077, 'max_depth': 6, 'num_leaves': 15, 'subsample': 0.745951039925051, 'colsample_bytree': 0.9307469243863349, 'min_child_samples': 86, 'reg_alpha': 4.607551042630673, 'reg_lambda': 1.2434303543142562}. Best is trial 13 with value: 20267.529911800157.
[I 2026-05-12 20:46:43,881] Trial 19 finished with value: 20063.982851812485 and parameters: {'n_estimators': 595, 'learning_rate': 0.012612850293075503, 'max_depth': 4, 'num_leaves': 186, 'subsample': 0.970781757771103, 'colsample_bytree': 0.9973855806392966, 'min_child_samples': 57, 'reg_alpha': 9.97525525456213, 'reg_lambda': 3.59653549765823}. Best is trial 19 with value: 20063.982851812485.
[I 2026-05-12 20:46:44,668] Trial 20 finished with value: 20040.06258192996 and parameters: {'n_estimators': 962, 'learning_rate': 0.007980699606292737, 'max_depth': 4, 'num_leaves': 187, 'subsample': 0.9993506434918653, 'colsample_bytree': 0.9844233013616348, 'min_child_samples': 29, 'reg_alpha': 0.11620961627553239, 'reg_lambda': 9.938427850497087}. Best is trial 20 with value: 20040.06258192996.
[I 2026-05-12 20:46:45,439] Trial 21 finished with value: 20050.312649046427 and parameters: {'n_estimators': 952, 'learning_rate': 0.00798027473782376, 'max_depth': 4, 'num_leaves': 191, 'subsample': 0.995177724690297, 'colsample_bytree': 0.9947131384209758, 'min_child_samples': 30, 'reg_alpha': 0.17358403505768827, 'reg_lambda': 7.090197191657357}. Best is trial 20 with value: 20040.06258192996.
[I 2026-05-12 20:46:46,269] Trial 22 finished with value: 20033.67299379665 and parameters: {'n_estimators': 990, 'learning_rate': 0.007486720933018243, 'max_depth': 4, 'num_leaves': 184, 'subsample': 0.997467298156202, 'colsample_bytree': 0.9975117572063534, 'min_child_samples': 28, 'reg_alpha': 0.12939161430282642, 'reg_lambda': 9.703798049018047}. Best is trial 22 with value: 20033.67299379665.
[I 2026-05-12 20:46:47,137] Trial 23 finished with value: 20051.15623827577 and parameters: {'n_estimators': 1060, 'learning_rate': 0.007528595010629971, 'max_depth': 4, 'num_leaves': 180, 'subsample': 0.9959367197967783, 'colsample_bytree': 0.9504574826933591, 'min_child_samples': 28, 'reg_alpha': 0.10134029079940618, 'reg_lambda': 9.548235119964875}. Best is trial 22 with value: 20033.67299379665.
[I 2026-05-12 20:46:47,931] Trial 24 finished with value: 20030.6493801495 and parameters: {'n_estimators': 932, 'learning_rate': 0.007732343182442615, 'max_depth': 4, 'num_leaves': 200, 'subsample': 0.9459090330913466, 'colsample_bytree': 0.9697457456839607, 'min_child_samples': 25, 'reg_alpha': 0.1260384258612212, 'reg_lambda': 9.888635204499057}. Best is trial 24 with value: 20030.6493801495.
[I 2026-05-12 20:46:51,762] Trial 25 finished with value: 20437.395588877793 and parameters: {'n_estimators': 1579, 'learning_rate': 0.005043678932110681, 'max_depth': 7, 'num_leaves': 127, 'subsample': 0.9398770580467641, 'colsample_bytree': 0.9540004349313833, 'min_child_samples': 22, 'reg_alpha': 1.2795852374379102, 'reg_lambda': 9.867829126131435}. Best is trial 24 with value: 20030.6493801495.
[I 2026-05-12 20:46:52,938] Trial 26 finished with value: 20129.880701062575 and parameters: {'n_estimators': 1396, 'learning_rate': 0.0065454771889418995, 'max_depth': 4, 'num_leaves': 169, 'subsample': 0.9593134449773638, 'colsample_bytree': 0.9050263264243316, 'min_child_samples': 17, 'reg_alpha': 1.406265274799001, 'reg_lambda': 7.5607720295226795}. Best is trial 24 with value: 20030.6493801495.
[I 2026-05-12 20:46:54,978] Trial 27 finished with value: 20429.021348022994 and parameters: {'n_estimators': 898, 'learning_rate': 0.008597822788843483, 'max_depth': 7, 'num_leaves': 207, 'subsample': 0.8912101550266425, 'colsample_bytree': 0.9675223686868637, 'min_child_samples': 34, 'reg_alpha': 2.256367224601117, 'reg_lambda': 9.253864897806048}. Best is trial 24 with value: 20030.6493801495.
[I 2026-05-12 20:46:55,425] Trial 28 finished with value: 21305.879841405087 and parameters: {'n_estimators': 463, 'learning_rate': 0.006123390221166898, 'max_depth': 4, 'num_leaves': 228, 'subsample': 0.9678289339035362, 'colsample_bytree': 0.9153972566252697, 'min_child_samples': 15, 'reg_alpha': 3.5942715021893004, 'reg_lambda': 9.838021881511782}. Best is trial 24 with value: 20030.6493801495.
[I 2026-05-12 20:46:57,807] Trial 29 finished with value: 20864.34137957044 and parameters: {'n_estimators': 1254, 'learning_rate': 0.011648120682493456, 'max_depth': 6, 'num_leaves': 150, 'subsample': 0.8785898387796973, 'colsample_bytree': 0.9698541722826695, 'min_child_samples': 6, 'reg_alpha': 0.7132376967381088, 'reg_lambda': 6.00241164751386}. Best is trial 24 with value: 20030.6493801495.
[I 2026-05-12 20:46:58,886] Trial 30 finished with value: 20495.699125333325 and parameters: {'n_estimators': 1791, 'learning_rate': 0.00857358260879029, 'max_depth': 3, 'num_leaves': 197, 'subsample': 0.9349349743780591, 'colsample_bytree': 0.928105658304223, 'min_child_samples': 41, 'reg_alpha': 1.963656585101648, 'reg_lambda': 9.158900184319503}. Best is trial 24 with value: 20030.6493801495.
[I 2026-05-12 20:46:59,697] Trial 31 finished with value: 20020.430613830005 and parameters: {'n_estimators': 937, 'learning_rate': 0.007791311812192606, 'max_depth': 4, 'num_leaves': 176, 'subsample': 0.9954627320949059, 'colsample_bytree': 0.9993134344664012, 'min_child_samples': 30, 'reg_alpha': 0.002015220146534741, 'reg_lambda': 7.285146928910762}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:05,228] Trial 32 finished with value: 20833.377545865424 and parameters: {'n_estimators': 916, 'learning_rate': 0.005931128852033489, 'max_depth': 12, 'num_leaves': 172, 'subsample': 0.9970877778362938, 'colsample_bytree': 0.9769174137222609, 'min_child_samples': 24, 'reg_alpha': 0.5893083495182534, 'reg_lambda': 7.955538476959893}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:06,470] Trial 33 finished with value: 20294.954080122065 and parameters: {'n_estimators': 1245, 'learning_rate': 0.008848829832843484, 'max_depth': 4, 'num_leaves': 207, 'subsample': 0.9553164823417777, 'colsample_bytree': 0.9969906700731707, 'min_child_samples': 30, 'reg_alpha': 1.824194833265208, 'reg_lambda': 6.210729191173828}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:08,045] Trial 34 finished with value: 20242.750212033065 and parameters: {'n_estimators': 1137, 'learning_rate': 0.007283714482104124, 'max_depth': 5, 'num_leaves': 233, 'subsample': 0.9832288117861915, 'colsample_bytree': 0.9588915273749357, 'min_child_samples': 17, 'reg_alpha': 0.7897705700020966, 'reg_lambda': 8.574026361440922}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:08,901] Trial 35 finished with value: 20360.37230550796 and parameters: {'n_estimators': 1531, 'learning_rate': 0.005652367751111963, 'max_depth': 3, 'num_leaves': 155, 'subsample': 0.9437880216372169, 'colsample_bytree': 0.7124756259501557, 'min_child_samples': 47, 'reg_alpha': 3.3098555707788697, 'reg_lambda': 7.513734870449913}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:09,310] Trial 36 finished with value: 20824.16190077717 and parameters: {'n_estimators': 490, 'learning_rate': 0.0065604015104767655, 'max_depth': 4, 'num_leaves': 139, 'subsample': 0.9090623900357921, 'colsample_bytree': 0.9722470926989762, 'min_child_samples': 14, 'reg_alpha': 0.055477447502236446, 'reg_lambda': 9.986409325592861}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:11,107] Trial 37 finished with value: 20953.773265623004 and parameters: {'n_estimators': 893, 'learning_rate': 0.016552950930499848, 'max_depth': 7, 'num_leaves': 202, 'subsample': 0.9718455738580059, 'colsample_bytree': 0.940897343386504, 'min_child_samples': 36, 'reg_alpha': 2.460682813522084, 'reg_lambda': 8.96270299263797}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:11,901] Trial 38 finished with value: 20449.48400669311 and parameters: {'n_estimators': 1371, 'learning_rate': 0.010087441709016083, 'max_depth': 3, 'num_leaves': 166, 'subsample': 0.9252964346112761, 'colsample_bytree': 0.9204710017940493, 'min_child_samples': 26, 'reg_alpha': 1.6495175833021576, 'reg_lambda': 5.035252546885162}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:14,604] Trial 39 finished with value: 21245.47754345866 and parameters: {'n_estimators': 2237, 'learning_rate': 0.011873878225896412, 'max_depth': 6, 'num_leaves': 181, 'subsample': 0.9788320166412874, 'colsample_bytree': 0.6802737588836538, 'min_child_samples': 47, 'reg_alpha': 0.8153194013752136, 'reg_lambda': 8.163020513124577}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:22,290] Trial 40 finished with value: 20850.230917297686 and parameters: {'n_estimators': 1708, 'learning_rate': 0.005319832810980317, 'max_depth': 10, 'num_leaves': 126, 'subsample': 0.8876853742714148, 'colsample_bytree': 0.9827780421778526, 'min_child_samples': 10, 'reg_alpha': 3.711402269576508, 'reg_lambda': 8.661727217656132}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:23,184] Trial 41 finished with value: 20059.22630002539 and parameters: {'n_estimators': 1021, 'learning_rate': 0.007909010866967733, 'max_depth': 4, 'num_leaves': 194, 'subsample': 0.9998773671411719, 'colsample_bytree': 0.9979435193118433, 'min_child_samples': 21, 'reg_alpha': 0.10658522808809474, 'reg_lambda': 6.82842414022766}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:28,058] Trial 42 finished with value: 20720.448432672507 and parameters: {'n_estimators': 872, 'learning_rate': 0.006738418779868648, 'max_depth': 11, 'num_leaves': 180, 'subsample': 0.9500110775009045, 'colsample_bytree': 0.9813312264499754, 'min_child_samples': 32, 'reg_alpha': 0.5758562736193267, 'reg_lambda': 9.368584849557223}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:28,991] Trial 43 finished with value: 20198.994312426836 and parameters: {'n_estimators': 1175, 'learning_rate': 0.008531084357924169, 'max_depth': 4, 'num_leaves': 160, 'subsample': 0.9880177264048284, 'colsample_bytree': 0.9560264267035251, 'min_child_samples': 39, 'reg_alpha': 0.366834157530703, 'reg_lambda': 7.094732834145904}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:29,614] Trial 44 finished with value: 20420.88910153256 and parameters: {'n_estimators': 992, 'learning_rate': 0.009502902837075038, 'max_depth': 3, 'num_leaves': 216, 'subsample': 0.9610968494763585, 'colsample_bytree': 0.9999824058089138, 'min_child_samples': 30, 'reg_alpha': 0.9787890533355252, 'reg_lambda': 5.424095699368888}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:30,574] Trial 45 finished with value: 20295.504760530777 and parameters: {'n_estimators': 826, 'learning_rate': 0.010723592922062285, 'max_depth': 5, 'num_leaves': 143, 'subsample': 0.9106055165031257, 'colsample_bytree': 0.9766317610702431, 'min_child_samples': 44, 'reg_alpha': 1.2394726951695738, 'reg_lambda': 4.234309570029073}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:32,636] Trial 46 finished with value: 20359.833151354913 and parameters: {'n_estimators': 541, 'learning_rate': 0.007870280520344834, 'max_depth': 9, 'num_leaves': 112, 'subsample': 0.9753461511648157, 'colsample_bytree': 0.9403267755422631, 'min_child_samples': 35, 'reg_alpha': 0.05629576451652692, 'reg_lambda': 6.285675411054974}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:34,248] Trial 47 finished with value: 20346.40784456246 and parameters: {'n_estimators': 1426, 'learning_rate': 0.007080368029465884, 'max_depth': 5, 'num_leaves': 190, 'subsample': 0.6430665877040956, 'colsample_bytree': 0.898987878977702, 'min_child_samples': 21, 'reg_alpha': 8.359030379476577, 'reg_lambda': 7.6942671904004625}. Best is trial 31 with value: 20020.430613830005.
[I 2026-05-12 20:47:34,679] Trial 48 finished with value: 21890.099510312626 and parameters: {'n_estimators': 721, 'learning_rate': 0.005651170140833049, 'max_depth': 3, 'num_leaves': 175, 'subsample': 0.9982134139595638, 'colsample_bytree': 0.9595183578843601, 'min_child_samples': 10, 'reg_alpha': 1.5619898866977062, 'reg_lambda': 8.603201357088716}. Best is trial 31 with value: 20020.430613830005.

========================================
MODEL      : lightgbm
BEST RMSE  : 20020.4306
BEST PARAMS:
{'n_estimators': 937, 'learning_rate': 0.007791311812192606, 'max_depth': 4, 'num_leaves': 176, 'subsample': 0.9954627320949059, 'colsample_bytree': 0.9993134344664012, 'min_child_samples': 30, 'reg_alpha': 0.002015220146534741, 'reg_lambda': 7.285146928910762}
========================================

In [71]:
xgb_best = optuna_xgboost(X_train, y_train, X_valid, y_valid, n_trials=50)

[I 2026-05-12 20:52:46,038] A new study created in memory with name: no-name-ad0e19b9-050b-4362-ac5a-790c3ac08205
[I 2026-05-12 20:52:50,481] Trial 0 finished with value: 21801.522498618615 and parameters: {'n_estimators': 1311, 'learning_rate': 0.044635901521768134, 'max_depth': 10, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.6624074561769746, 'min_child_weight': 4, 'gamma': 0.5808361216819946, 'reg_alpha': 8.661761457749352, 'reg_lambda': 6.011150117432088}. Best is trial 0 with value: 21801.522498618615.
[I 2026-05-12 20:53:01,662] Trial 1 finished with value: 21190.239331705667 and parameters: {'n_estimators': 2212, 'learning_rate': 0.005242693862597309, 'max_depth': 12, 'subsample': 0.9329770563201687, 'colsample_bytree': 0.6849356442713105, 'min_child_weight': 4, 'gamma': 1.8340450985343382, 'reg_alpha': 3.0424224295953772, 'reg_lambda': 5.247564316322379}. Best is trial 1 with value: 21190.239331705667.
[I 2026-05-12 20:53:05,447] Trial 2 finished with value: 21254.024329341137 and parameters: {'n_estimators': 1466, 'learning_rate': 0.009776854331372627, 'max_depth': 9, 'subsample': 0.6557975442608167, 'colsample_bytree': 0.7168578594140873, 'min_child_weight': 8, 'gamma': 4.56069984217036, 'reg_alpha': 7.851759613930136, 'reg_lambda': 1.9967378215835974}. Best is trial 1 with value: 21190.239331705667.
[I 2026-05-12 20:53:06,658] Trial 3 finished with value: 20546.14064043465 and parameters: {'n_estimators': 1688, 'learning_rate': 0.019560708142748476, 'max_depth': 3, 'subsample': 0.8430179407605753, 'colsample_bytree': 0.6682096494749166, 'min_child_weight': 2, 'gamma': 9.488855372533333, 'reg_alpha': 9.656320330745594, 'reg_lambda': 8.08397348116461}. Best is trial 3 with value: 20546.14064043465.
[I 2026-05-12 20:53:09,343] Trial 4 finished with value: 20587.303819688652 and parameters: {'n_estimators': 1122, 'learning_rate': 0.006260977143530196, 'max_depth': 9, 'subsample': 0.7760609974958406, 'colsample_bytree': 0.6488152939379115, 'min_child_weight': 10, 'gamma': 0.34388521115218396, 'reg_alpha': 9.093204020787821, 'reg_lambda': 2.587799816000169}. Best is trial 3 with value: 20546.14064043465.
[I 2026-05-12 20:53:12,752] Trial 5 finished with value: 21264.492646102408 and parameters: {'n_estimators': 2089, 'learning_rate': 0.010248990260475094, 'max_depth': 8, 'subsample': 0.8186841117373118, 'colsample_bytree': 0.6739417822102108, 'min_child_weight': 20, 'gamma': 7.7513282336111455, 'reg_alpha': 9.394989415641891, 'reg_lambda': 8.948273504276488}. Best is trial 3 with value: 20546.14064043465.
[I 2026-05-12 20:53:14,300] Trial 6 finished with value: 20847.1181774952 and parameters: {'n_estimators': 1914, 'learning_rate': 0.0417680537765588, 'max_depth': 3, 'subsample': 0.6783931449676581, 'colsample_bytree': 0.6180909155642152, 'min_child_weight': 7, 'gamma': 3.8867728968948203, 'reg_alpha': 2.713490317738959, 'reg_lambda': 8.287375091519294}. Best is trial 3 with value: 20546.14064043465.
[I 2026-05-12 20:53:17,357] Trial 7 finished with value: 21030.226529967953 and parameters: {'n_estimators': 1263, 'learning_rate': 0.009547826400522689, 'max_depth': 8, 'subsample': 0.6563696899899051, 'colsample_bytree': 0.9208787923016158, 'min_child_weight': 2, 'gamma': 9.868869366005173, 'reg_alpha': 7.722447692966574, 'reg_lambda': 1.987156815341724}. Best is trial 3 with value: 20546.14064043465.
[I 2026-05-12 20:53:18,804] Trial 8 finished with value: 21035.2174066901 and parameters: {'n_estimators': 314, 'learning_rate': 0.03269124292259021, 'max_depth': 10, 'subsample': 0.8916028672163949, 'colsample_bytree': 0.9085081386743783, 'min_child_weight': 2, 'gamma': 3.5846572854427263, 'reg_alpha': 1.1586905952512971, 'reg_lambda': 8.631034258755935}. Best is trial 3 with value: 20546.14064043465.
[I 2026-05-12 20:53:21,206] Trial 9 finished with value: 20467.281533769605 and parameters: {'n_estimators': 1983, 'learning_rate': 0.010711937478224529, 'max_depth': 3, 'subsample': 0.7243929286862649, 'colsample_bytree': 0.7300733288106989, 'min_child_weight': 15, 'gamma': 6.3755747135521315, 'reg_alpha': 8.872127425763265, 'reg_lambda': 4.722149251619493}. Best is trial 9 with value: 20467.281533769605.
[I 2026-05-12 20:53:24,714] Trial 10 finished with value: 21479.600939979395 and parameters: {'n_estimators': 2885, 'learning_rate': 0.019484776564044022, 'max_depth': 5, 'subsample': 0.7387403565626488, 'colsample_bytree': 0.8010124870699186, 'min_child_weight': 16, 'gamma': 6.543765227707531, 'reg_alpha': 6.18718032094214, 'reg_lambda': 3.7200432627265183}. Best is trial 9 with value: 20467.281533769605.
[I 2026-05-12 20:53:26,931] Trial 11 finished with value: 20726.365546285353 and parameters: {'n_estimators': 2581, 'learning_rate': 0.018808482060509096, 'max_depth': 3, 'subsample': 0.7382135623933878, 'colsample_bytree': 0.7737425087025644, 'min_child_weight': 15, 'gamma': 9.55566704339899, 'reg_alpha': 6.071842740332256, 'reg_lambda': 6.880988980130585}. Best is trial 9 with value: 20467.281533769605.
[I 2026-05-12 20:53:27,842] Trial 12 finished with value: 20344.056446856994 and parameters: {'n_estimators': 722, 'learning_rate': 0.014335938848538895, 'max_depth': 5, 'subsample': 0.9983624361463618, 'colsample_bytree': 0.7668689715046754, 'min_child_weight': 14, 'gamma': 7.0116259539376, 'reg_alpha': 9.902412260216211, 'reg_lambda': 0.30925226388650984}. Best is trial 12 with value: 20344.056446856994.
[I 2026-05-12 20:53:28,572] Trial 13 finished with value: 20352.470792003947 and parameters: {'n_estimators': 669, 'learning_rate': 0.013477450689285447, 'max_depth': 5, 'subsample': 0.9997449754566203, 'colsample_bytree': 0.8259247350993981, 'min_child_weight': 15, 'gamma': 6.521603008527053, 'reg_alpha': 6.802998308648532, 'reg_lambda': 0.3286995785803954}. Best is trial 12 with value: 20344.056446856994.
[I 2026-05-12 20:53:29,388] Trial 14 finished with value: 20887.788790185634 and parameters: {'n_estimators': 606, 'learning_rate': 0.0288621869131641, 'max_depth': 6, 'subsample': 0.9984067957444853, 'colsample_bytree': 0.8457495422882018, 'min_child_weight': 13, 'gamma': 7.585334662097706, 'reg_alpha': 4.665740730554513, 'reg_lambda': 0.27405700502154856}. Best is trial 12 with value: 20344.056446856994.
[I 2026-05-12 20:53:30,349] Trial 15 finished with value: 20406.981525758692 and parameters: {'n_estimators': 749, 'learning_rate': 0.014193823249058763, 'max_depth': 5, 'subsample': 0.9792324269995094, 'colsample_bytree': 0.8561711433906496, 'min_child_weight': 19, 'gamma': 5.935088712419169, 'reg_alpha': 6.705451426048862, 'reg_lambda': 0.24779127567149034}. Best is trial 12 with value: 20344.056446856994.
[I 2026-05-12 20:53:31,424] Trial 16 finished with value: 20533.19239930429 and parameters: {'n_estimators': 782, 'learning_rate': 0.014085660474225126, 'max_depth': 6, 'subsample': 0.9325560457495446, 'colsample_bytree': 0.7911302960155628, 'min_child_weight': 12, 'gamma': 7.845886982879996, 'reg_alpha': 5.198679195412575, 'reg_lambda': 0.992616220694832}. Best is trial 12 with value: 20344.056446856994.
[I 2026-05-12 20:53:31,816] Trial 17 finished with value: 21605.321847399126 and parameters: {'n_estimators': 325, 'learning_rate': 0.007301448004505651, 'max_depth': 5, 'subsample': 0.9406457761768029, 'colsample_bytree': 0.8505915654206465, 'min_child_weight': 17, 'gamma': 5.06776256871667, 'reg_alpha': 7.3555051811565635, 'reg_lambda': 3.3405076606543123}. Best is trial 12 with value: 20344.056446856994.
[I 2026-05-12 20:53:33,219] Trial 18 finished with value: 21185.387991777137 and parameters: {'n_estimators': 1067, 'learning_rate': 0.026443898966806077, 'max_depth': 6, 'subsample': 0.6011669787775515, 'colsample_bytree': 0.745951039925051, 'min_child_weight': 13, 'gamma': 8.5151651780669, 'reg_alpha': 4.607551042630673, 'reg_lambda': 1.2434303543142562}. Best is trial 12 with value: 20344.056446856994.
[I 2026-05-12 20:53:33,812] Trial 19 finished with value: 20019.02744792925 and parameters: {'n_estimators': 595, 'learning_rate': 0.012612850293075503, 'max_depth': 4, 'subsample': 0.8855774490520028, 'colsample_bytree': 0.970781757771103, 'min_child_weight': 18, 'gamma': 2.5624037160924096, 'reg_alpha': 9.97525525456213, 'reg_lambda': 3.59653549765823}. Best is trial 19 with value: 20019.02744792925.
[I 2026-05-12 20:53:34,685] Trial 20 finished with value: 20017.08209895784 and parameters: {'n_estimators': 953, 'learning_rate': 0.0075712914022816906, 'max_depth': 4, 'subsample': 0.8796003477500673, 'colsample_bytree': 0.999267503989426, 'min_child_weight': 18, 'gamma': 2.5997423016857732, 'reg_alpha': 0.11620961627553239, 'reg_lambda': 9.938427850497087}. Best is trial 20 with value: 20017.08209895784.
[I 2026-05-12 20:53:35,602] Trial 21 finished with value: 20006.05296521337 and parameters: {'n_estimators': 952, 'learning_rate': 0.007761300561564391, 'max_depth': 4, 'subsample': 0.8921574385683139, 'colsample_bytree': 0.9945574194515999, 'min_child_weight': 18, 'gamma': 2.1671198531172444, 'reg_alpha': 0.17358403505768827, 'reg_lambda': 7.090197191657357}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:36,513] Trial 22 finished with value: 20031.888967920782 and parameters: {'n_estimators': 988, 'learning_rate': 0.007935455201586377, 'max_depth': 4, 'subsample': 0.8803301219613214, 'colsample_bytree': 0.9974652302011374, 'min_child_weight': 18, 'gamma': 2.407077611102552, 'reg_alpha': 0.12939161430282642, 'reg_lambda': 9.703798049018047}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:37,375] Trial 23 finished with value: 20007.95728949456 and parameters: {'n_estimators': 937, 'learning_rate': 0.007701197120960137, 'max_depth': 4, 'subsample': 0.8837745503693216, 'colsample_bytree': 0.9903722004067025, 'min_child_weight': 20, 'gamma': 2.0798120416100163, 'reg_alpha': 0.04455616525587944, 'reg_lambda': 7.065410466488581}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:38,873] Trial 24 finished with value: 20041.097150962618 and parameters: {'n_estimators': 1548, 'learning_rate': 0.005027627707218086, 'max_depth': 4, 'subsample': 0.8602807832369572, 'colsample_bytree': 0.9458779328899113, 'min_child_weight': 20, 'gamma': 1.3577593415552798, 'reg_alpha': 0.12192179644871082, 'reg_lambda': 7.068329287099644}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:40,603] Trial 25 finished with value: 20501.43596323494 and parameters: {'n_estimators': 1028, 'learning_rate': 0.0078093237269985264, 'max_depth': 7, 'subsample': 0.7918533730439762, 'colsample_bytree': 0.9902115584713334, 'min_child_weight': 17, 'gamma': 3.2291630204363706, 'reg_alpha': 1.2795852374379102, 'reg_lambda': 7.425861996287187}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:41,424] Trial 26 finished with value: 20046.937631911525 and parameters: {'n_estimators': 902, 'learning_rate': 0.006277223430488311, 'max_depth': 4, 'subsample': 0.9090800650840611, 'colsample_bytree': 0.8923999425709396, 'min_child_weight': 20, 'gamma': 1.2652268937123567, 'reg_alpha': 1.2495915494777232, 'reg_lambda': 9.796830996079875}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:43,554] Trial 27 finished with value: 20524.670989457572 and parameters: {'n_estimators': 1259, 'learning_rate': 0.006431956629188345, 'max_depth': 7, 'subsample': 0.818790070897464, 'colsample_bytree': 0.9493151838740905, 'min_child_weight': 18, 'gamma': 2.5773946425852245, 'reg_alpha': 2.2520384650992282, 'reg_lambda': 6.094934702074953}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:45,315] Trial 28 finished with value: 20379.714704809932 and parameters: {'n_estimators': 1767, 'learning_rate': 0.00867318687475327, 'max_depth': 4, 'subsample': 0.9553803649074253, 'colsample_bytree': 0.9541323740700989, 'min_child_weight': 10, 'gamma': 4.431029228151999, 'reg_alpha': 0.6686104992032126, 'reg_lambda': 7.6318717083415955}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:47,235] Trial 29 finished with value: 20847.99025688998 and parameters: {'n_estimators': 1426, 'learning_rate': 0.011846042268390717, 'max_depth': 6, 'subsample': 0.851060922387381, 'colsample_bytree': 0.878540543474706, 'min_child_weight': 17, 'gamma': 0.8244702588536803, 'reg_alpha': 2.000374097838486, 'reg_lambda': 6.00241164751386}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:47,731] Trial 30 finished with value: 23020.94541899265 and parameters: {'n_estimators': 479, 'learning_rate': 0.006924872759508727, 'max_depth': 3, 'subsample': 0.9108924757768613, 'colsample_bytree': 0.9263419035659848, 'min_child_weight': 19, 'gamma': 0.04896217498273803, 'reg_alpha': 3.7195034331262784, 'reg_lambda': 6.342725019229247}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:48,398] Trial 31 finished with value: 20010.256906784878 and parameters: {'n_estimators': 492, 'learning_rate': 0.011913824203570627, 'max_depth': 4, 'subsample': 0.8755018207309047, 'colsample_bytree': 0.977383284952236, 'min_child_weight': 18, 'gamma': 2.6464260175347984, 'reg_alpha': 0.005411220270206435, 'reg_lambda': 4.291819584918944}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:51,758] Trial 32 finished with value: 21182.217016706752 and parameters: {'n_estimators': 896, 'learning_rate': 0.008542696280743197, 'max_depth': 12, 'subsample': 0.8685302118843543, 'colsample_bytree': 0.9764067625655848, 'min_child_weight': 19, 'gamma': 1.7935112115438034, 'reg_alpha': 0.5887703617906848, 'reg_lambda': 5.240498164499757}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:52,211] Trial 33 finished with value: 21668.627567361556 and parameters: {'n_estimators': 456, 'learning_rate': 0.005676876495923554, 'max_depth': 4, 'subsample': 0.9086196564007715, 'colsample_bytree': 0.9928659818705448, 'min_child_weight': 16, 'gamma': 3.0945905530490787, 'reg_alpha': 1.7829603758014432, 'reg_lambda': 4.404996789337472}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:53,467] Trial 34 finished with value: 20841.029684867004 and parameters: {'n_estimators': 1142, 'learning_rate': 0.016610840923564546, 'max_depth': 5, 'subsample': 0.8290973248460496, 'colsample_bytree': 0.9644781324229766, 'min_child_weight': 8, 'gamma': 1.9225117429339678, 'reg_alpha': 0.7907528788158299, 'reg_lambda': 9.246138543040578}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:54,609] Trial 35 finished with value: 20463.353101656485 and parameters: {'n_estimators': 1396, 'learning_rate': 0.011169302578859829, 'max_depth': 3, 'subsample': 0.9508972554891802, 'colsample_bytree': 0.946779855157621, 'min_child_weight': 16, 'gamma': 1.0075057016213018, 'reg_alpha': 3.3098555707788697, 'reg_lambda': 5.675271910955734}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:55,121] Trial 36 finished with value: 20171.517873798064 and parameters: {'n_estimators': 499, 'learning_rate': 0.008971280315764307, 'max_depth': 4, 'subsample': 0.7963098619921458, 'colsample_bytree': 0.99881662122187, 'min_child_weight': 20, 'gamma': 4.174249811734262, 'reg_alpha': 0.053349315653268885, 'reg_lambda': 4.375501459633354}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:56,523] Trial 37 finished with value: 20248.29635187601 and parameters: {'n_estimators': 866, 'learning_rate': 0.0057968843023718285, 'max_depth': 7, 'subsample': 0.851850005046099, 'colsample_bytree': 0.9275801077590898, 'min_child_weight': 18, 'gamma': 5.163131354248728, 'reg_alpha': 1.5266042546635985, 'reg_lambda': 8.17788906362509}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:53:57,488] Trial 38 finished with value: 20406.805743674347 and parameters: {'n_estimators': 1181, 'learning_rate': 0.00987579118650257, 'max_depth': 3, 'subsample': 0.7684289414339478, 'colsample_bytree': 0.9702497621672519, 'min_child_weight': 5, 'gamma': 1.864435321319615, 'reg_alpha': 2.639734725678203, 'reg_lambda': 2.8913922214652956}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:54:00,289] Trial 39 finished with value: 20922.956265051267 and parameters: {'n_estimators': 2237, 'learning_rate': 0.007383628431895759, 'max_depth': 6, 'subsample': 0.9239873212369583, 'colsample_bytree': 0.9010079883254187, 'min_child_weight': 11, 'gamma': 3.4022410272152026, 'reg_alpha': 0.5797270271223436, 'reg_lambda': 6.595620341039768}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:54:04,937] Trial 40 finished with value: 21097.855165320627 and parameters: {'n_estimators': 1557, 'learning_rate': 0.005664782693620013, 'max_depth': 10, 'subsample': 0.8353669943923459, 'colsample_bytree': 0.9345003758228841, 'min_child_weight': 19, 'gamma': 2.8525419778199432, 'reg_alpha': 0.8704982852998808, 'reg_lambda': 5.495966962383409}. Best is trial 21 with value: 20006.05296521337.
[I 2026-05-12 20:54:05,504] Trial 41 finished with value: 19990.32204992378 and parameters: {'n_estimators': 578, 'learning_rate': 0.011690156280708838, 'max_depth': 4, 'subsample': 0.8877027290749933, 'colsample_bytree': 0.974481026311757, 'min_child_weight': 18, 'gamma': 1.9207645291808602, 'reg_alpha': 8.537671637807994, 'reg_lambda': 3.92228062985356}. Best is trial 41 with value: 19990.32204992378.
[I 2026-05-12 20:54:06,784] Trial 42 finished with value: 20491.293449735247 and parameters: {'n_estimators': 365, 'learning_rate': 0.010557882511910756, 'max_depth': 11, 'subsample': 0.8882217911056857, 'colsample_bytree': 0.9756613947688441, 'min_child_weight': 17, 'gamma': 0.5189661988900798, 'reg_alpha': 8.596350684621385, 'reg_lambda': 4.025682925385547}. Best is trial 41 with value: 19990.32204992378.
[I 2026-05-12 20:54:07,371] Trial 43 finished with value: 20189.10488772002 and parameters: {'n_estimators': 619, 'learning_rate': 0.016316377080686423, 'max_depth': 4, 'subsample': 0.8648826811704433, 'colsample_bytree': 0.9880053917423625, 'min_child_weight': 20, 'gamma': 2.1525514203632854, 'reg_alpha': 0.3457493740708347, 'reg_lambda': 4.957858782760381}. Best is trial 41 with value: 19990.32204992378.
[I 2026-05-12 20:54:08,024] Trial 44 finished with value: 20459.19458998491 and parameters: {'n_estimators': 827, 'learning_rate': 0.012059878406595451, 'max_depth': 3, 'subsample': 0.9010050385796947, 'colsample_bytree': 0.9609559551174768, 'min_child_weight': 14, 'gamma': 1.49663795665167, 'reg_alpha': 0.9787890533355252, 'reg_lambda': 8.911298096931278}. Best is trial 41 with value: 19990.32204992378.
[I 2026-05-12 20:54:09,024] Trial 45 finished with value: 20331.75667990563 and parameters: {'n_estimators': 978, 'learning_rate': 0.00949017842633549, 'max_depth': 5, 'subsample': 0.9609876644412108, 'colsample_bytree': 0.877760559320147, 'min_child_weight': 16, 'gamma': 2.785071007097597, 'reg_alpha': 1.554550726771546, 'reg_lambda': 2.5147186650894446}. Best is trial 41 with value: 19990.32204992378.
[I 2026-05-12 20:54:10,230] Trial 46 finished with value: 20228.309889088836 and parameters: {'n_estimators': 502, 'learning_rate': 0.006819046213564626, 'max_depth': 9, 'subsample': 0.8749444729342643, 'colsample_bytree': 0.915235441428287, 'min_child_weight': 18, 'gamma': 3.6026864570691295, 'reg_alpha': 4.099668976204712, 'reg_lambda': 7.673578735046814}. Best is trial 41 with value: 19990.32204992378.
[I 2026-05-12 20:54:10,923] Trial 47 finished with value: 20461.45893152904 and parameters: {'n_estimators': 680, 'learning_rate': 0.02160599614081155, 'max_depth': 5, 'subsample': 0.841760786807883, 'colsample_bytree': 0.6430665877040956, 'min_child_weight': 19, 'gamma': 2.204277054912356, 'reg_alpha': 8.359030379476577, 'reg_lambda': 3.09104042474768}. Best is trial 41 with value: 19990.32204992378.

========================================
MODEL      : xgboost
BEST RMSE  : 19990.3220
BEST PARAMS:
{'n_estimators': 578, 'learning_rate': 0.011690156280708838, 'max_depth': 4, 'subsample': 0.8877027290749933, 'colsample_bytree': 0.974481026311757, 'min_child_weight': 18, 'gamma': 1.9207645291808602, 'reg_alpha': 8.537671637807994, 'reg_lambda': 3.92228062985356}
========================================

In [73]:
X_train, X_test, y_train, y_test, _ = split_train_test(df_2011, 'total_load', split_time="2014-01-01", categorical_cols='holiday_name')

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (26328, 10)
Test shape: (8759, 10)

In [74]:
rdf, rdf_pred = random_forest_model(X_train, y_train, X_test, rdf_best.best_params)
rdf_metrics = evaluate(y_test, rdf_pred)

print("Random Forest:", rdf_metrics)

Random Forest: {'MAE': 13093.43, 'RMSE': 18439.95, 'MAPE': 5.75}

In [76]:
lgbm, lgbm_pred = lightgbm_model(X_train, y_train, X_test, lgbm_best.best_params)
lgbm_metrics = evaluate(y_test, lgbm_pred)

print("LightGBM:", lgbm_metrics)

LightGBM: {'MAE': 13063.47, 'RMSE': 18310.15, 'MAPE': 5.71}

In [77]:
xgb, xgb_pred = xgboost_model(X_train, y_train, X_test, xgb_best.best_params)
xgb_metrics = evaluate(y_test, xgb_pred)

print("XGBoost:", xgb_metrics)

XGBoost: {'MAE': 14012.4, 'RMSE': 19834.35, 'MAPE': 6.01}

## 5. Tổng hợp và So sánh Kết quả (Compare)

Dưới đây là bảng tổng hợp hiệu suất của các mô hình qua 3 giai đoạn: Trước khi có dữ liệu 2011, Sau khi phục dựng 2011 (thêm features), và Sau khi tinh chỉnh siêu tham số (Hyperparameter Tuning).

| Giai đoạn | Mô hình | MAE | RMSE | MAPE (%) |
| :--- | :--- | :--- | :--- | :--- |
| **Baseline** | Seasonal Naive (24h) | 14,598.19 | 21,626.90 | 6.07 |
| | | | | |
| **Thiếu năm 2011** | Random Forest / Base 1 | 13,265.68 | 19,425.27 | 5.56 |
| | LightGBM | 13,629.68 | 19,854.71 | 5.80 |
| | XGBoost | 13,570.01 | 20,275.23 | 5.63 |
| | | | | |
| **Có năm 2011 (Backcast)** | Random Forest | **12,828.45** | 18,776.22 | **5.36** |
|  | LightGBM | 13,012.48 | 18,869.57 | 5.58 |
| | XGBoost | 12,965.75 | 19,446.47 | 5.37 |
| | | | | |
| **Sau Tối ưu hóa (Optuna)** | Random Forest (Tuned) | 13,093.43 | 18,439.95 | 5.75 |
| *(Mục tiêu: Min RMSE)* | LightGBM (Tuned) | 13,063.47 | **18,310.15** | 5.71 |
| | XGBoost (Tuned) | 14,012.40 | 19,834.35 | 6.01 |